server:
  port: 8084

spring:
  datasource:
    url: jdbc:oracle:thin:@//oracle-db:1521/XEPDB1
    username: report_user
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092,kafka2:9092,kafka3:9092
    consumer:
      group-id: report-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${TENANT_ID}/v2.0

campuslab:
  kafka:
    topic-events: bookings.events
    topic-dlt: report.DLT