server:
  port: 8084

spring:
  application:
    name: ms-campuslab-report

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/bookings_db
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  cache:
    type: simple

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/<TENANT_ID>/v2.0
